version: '3'
services: null
db:
  environment:
    POSTGRES_DB: todoNext
    POSTGRES_PASSWORD: root
    POSTGRES_USER: user4460
  image: postgres
  ports:
    - '5432:5432'
  restart: always
  volumes:
    - 'db-data:/var/lib/postgresql/data'